---

- name: Restart Service 'jenkins'
  service:
    name: jenkins
    state: restarted
  become: true
  notify: Wait for Jenkins HTTP

- name: Wait for Jenkins HTTP
  uri:
    url: "http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }}/login"
    status_code: 200
  register: jenkins_login_page
  until: jenkins_login_page.status == 200
  retries: 60
  delay: 1
